"""
StudyFlow FastAPI Local AI Backend
PDF/TXT summarization + NLP-guided MCQ and written quiz generation with Ollama.

Designed for:
- Windows
- CPU only
- 8GB RAM
- Local Ollama models

Important:
- Summary model stays qwen3:1.7b by default.
- Quiz model is changed to phi4-mini:latest by default.
- MCQ and written quiz questions are generated by the LLM, not by hardcoded templates.
- NLP/local code is used only for selecting useful source context and quality-checking output.
"""

from __future__ import annotations

import json
import logging
import os
import re
import time
from typing import Any, Optional, List

import fitz
import requests
from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field


# =========================================================
# CONFIG
# =========================================================

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

SUMMARY_MODEL = os.getenv("SUMMARY_MODEL", "qwen3:1.7b")
QUIZ_MODEL = os.getenv("QUIZ_MODEL", "phi4-mini:latest")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434").rstrip("/")

MAX_QUIZ_QUESTIONS = 5

# 8GB RAM friendly settings.
SUMMARY_CHUNK_CHARS_SMALL = 3000
SUMMARY_CHUNK_CHARS_MEDIUM = 4500
SUMMARY_CHUNK_CHARS_LARGE = 5000

QUIZ_MAX_CONTEXT_CHARS = int(os.getenv("QUIZ_MAX_CONTEXT_CHARS", "2300"))
QUIZ_NUM_CTX = int(os.getenv("QUIZ_NUM_CTX", "3072"))
QUIZ_NUM_PREDICT = int(os.getenv("QUIZ_NUM_PREDICT", "1150"))
OLLAMA_TIMEOUT_SECONDS = int(os.getenv("OLLAMA_TIMEOUT_SECONDS", "600"))


# =========================================================
# SCHEMAS
# =========================================================

class Input(BaseModel):
    human_input: str


class SummaryInput(BaseModel):
    text: Optional[str] = None
    human_input: Optional[str] = None


class SummaryOutput(BaseModel):
    output: str
    summary: str
    result: str
    processing_time_seconds: Optional[float] = None
    processing_time_minutes: Optional[float] = None


class QuizInput(BaseModel):
    text: str
    number_of_questions: int = 5
    difficulty: str = "Medium"


class QuizQuestion(BaseModel):
    question: str
    option_a: str
    option_b: str
    option_c: str
    option_d: str
    correct_answer: str
    correct_answer_text: str
    explanation: str


class QuizOutput(BaseModel):
    questions: List[QuizQuestion]
    processing_time_seconds: Optional[float] = None
    processing_time_minutes: Optional[float] = None
    raw_output: Optional[str] = None


class WrittenQuizInput(BaseModel):
    text: str
    number_of_questions: int = 5
    difficulty: str = "Mixed"


class WrittenQuestion(BaseModel):
    question: str
    difficulty: str
    expected_answer: str
    keywords: List[str] = Field(default_factory=list)
    grading_points: List[str] = Field(default_factory=list)
    page: Optional[str] = None
    explanation: str = ""


class WrittenQuizOutput(BaseModel):
    questions: List[WrittenQuestion]
    processing_time_seconds: Optional[float] = None
    processing_time_minutes: Optional[float] = None
    raw_output: Optional[str] = None


class WrittenUserAnswer(BaseModel):
    question: str
    user_answer: str
    expected_answer: str
    keywords: List[str] = Field(default_factory=list)
    grading_points: List[str] = Field(default_factory=list)
    page: Optional[str] = None
    explanation: Optional[str] = None


class WrittenGradeInput(BaseModel):
    answers: List[WrittenUserAnswer]


class SentenceFeedback(BaseModel):
    sentence: str
    is_correct: bool
    confidence: float
    matched_keywords: List[str] = Field(default_factory=list)
    comment: str


class WrittenAnswerGrade(BaseModel):
    question: str
    user_answer: str
    score: float
    status: str
    matched_keywords: List[str] = Field(default_factory=list)
    missing_keywords: List[str] = Field(default_factory=list)
    matched_points: List[str] = Field(default_factory=list)
    missing_points: List[str] = Field(default_factory=list)
    sentence_feedback: List[SentenceFeedback] = Field(default_factory=list)
    expected_answer: str
    explanation: str = ""
    page: Optional[str] = None


class WrittenGradeOutput(BaseModel):
    total_score: float
    percentage: float
    results: List[WrittenAnswerGrade]


# =========================================================
# APP
# =========================================================

app = FastAPI(title="StudyFlow Local AI Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =========================================================
# GENERAL HELPERS
# =========================================================

def model_to_dict(model: Any) -> dict:
    try:
        return model.model_dump()
    except Exception:
        return model.dict()


def clean_model_output(text: str) -> str:
    if not text:
        return ""
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"```(?:json|text|python)?", "", text, flags=re.IGNORECASE)
    text = text.replace("```", "")
    return text.strip()


def clean_quiz_part(text: Any) -> str:
    text = str(text or "").strip()
    text = re.sub(r"^[A-Da-d]\s*[\)\.\:\-]\s*", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def normalize_difficulty(difficulty: str) -> str:
    value = (difficulty or "Medium").strip().lower()

    if value in [
        "mixed", "mix", "mixed level", "advanced", "advance", "professor",
        "professor hard", "hard advanced", "advanced hard", "level 3",
        "very hard", "expert",
    ]:
        return "Mixed"

    if value in ["hard", "h", "level 2", "difficult"]:
        return "Hard"

    return "Medium"


def display_difficulty(difficulty: str) -> str:
    return normalize_difficulty(difficulty)


def clamp_question_count(value: Any) -> int:
    try:
        value = int(value)
    except Exception:
        value = 5
    return max(1, min(value, MAX_QUIZ_QUESTIONS))


def is_pdf_file(uploaded_file: UploadFile) -> bool:
    filename = (uploaded_file.filename or "").lower()
    content_type = (uploaded_file.content_type or "").lower()
    return content_type == "application/pdf" or filename.endswith(".pdf")


def is_txt_file(uploaded_file: UploadFile) -> bool:
    filename = (uploaded_file.filename or "").lower()
    content_type = (uploaded_file.content_type or "").lower()
    return content_type.startswith("text/plain") or filename.endswith(".txt") or filename.endswith(".text")


def decode_txt_bytes(file_bytes: bytes) -> str:
    if not file_bytes:
        return ""

    for encoding in ["utf-8", "utf-8-sig", "latin-1"]:
        try:
            return file_bytes.decode(encoding)
        except UnicodeDecodeError:
            continue

    return file_bytes.decode("latin-1", errors="ignore")


def clean_source_text(text: str) -> str:
    if not text:
        return ""

    text = clean_model_output(text)
    text = text.replace("\x00", " ")
    text = re.sub(r"[ \t]+", " ", text)

    generic_noise = [
        "copyright", "all rights reserved", "references", "bibliography", "index",
        "www.", "http://", "https://",
    ]

    cleaned_lines: list[str] = []

    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue

        low = line.lower()

        if re.fullmatch(r"---\s*page\s*\d+\s*---", low, flags=re.IGNORECASE):
            cleaned_lines.append(line)
            continue

        if any(noise in low for noise in generic_noise):
            continue
        if re.fullmatch(r"\d{1,4}", line):
            continue
        if len(line) <= 2:
            continue

        cleaned_lines.append(line)

    text = "\n".join(cleaned_lines)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def extract_pdf_text(file_bytes: bytes) -> str:
    try:
        pdf_document = fitz.open("pdf", file_bytes)
        pages_text: list[str] = []

        for page_index, page in enumerate(pdf_document, start=1):
            text = page.get_text("text")
            if text and text.strip():
                pages_text.append(f"\n--- PAGE {page_index} ---\n{text.strip()}")

        pdf_document.close()
        return clean_source_text("\n\n".join(pages_text))
    except Exception as e:
        logger.exception(f"PDF text extraction failed: {e}")
        return ""


def call_ollama_generate(
    prompt: str,
    model: str,
    format_json: bool = False,
    timeout: int = OLLAMA_TIMEOUT_SECONDS,
    num_ctx: int = 3072,
    num_predict: int = 1200,
    temperature: float = 0.1,
    top_p: float = 0.85,
    repeat_penalty: float = 1.12,
) -> str:
    payload: dict[str, Any] = {
        "model": model,
        "prompt": "/no_think\n" + prompt.strip(),
        "stream": True,
        "think": False,
        "keep_alive": "10m",
        "options": {
            "temperature": temperature,
            "top_p": top_p,
            "repeat_penalty": repeat_penalty,
            "num_ctx": num_ctx,
            "num_predict": num_predict,
        },
    }

    if format_json:
        payload["format"] = "json"

    parts: list[str] = []

    try:
        with requests.post(
            f"{OLLAMA_BASE_URL}/api/generate",
            json=payload,
            stream=True,
            timeout=(20, timeout),
        ) as response:
            if response.status_code == 404:
                raise HTTPException(
                    status_code=404,
                    detail=(
                        f"Ollama model not found: {model}. Run: ollama pull {model} "
                        "or change QUIZ_MODEL/SUMMARY_MODEL to the exact name from ollama list."
                    ),
                )

            response.raise_for_status()

            for line in response.iter_lines(decode_unicode=True):
                if not line:
                    continue
                try:
                    item = json.loads(line)
                except Exception:
                    continue

                if "response" in item:
                    parts.append(item.get("response") or "")

                if item.get("done") is True:
                    break

    except HTTPException:
        raise
    except requests.exceptions.ReadTimeout as e:
        raise HTTPException(
            status_code=504,
            detail=(
                "Ollama took too long. Try fewer questions, a smaller PDF section, "
                "or restart Ollama and try again."
            ),
        ) from e
    except requests.exceptions.ConnectionError as e:
        raise HTTPException(
            status_code=503,
            detail="Cannot connect to Ollama. Make sure Ollama is running on http://127.0.0.1:11434.",
        ) from e
    except requests.exceptions.RequestException as e:
        raise HTTPException(status_code=500, detail=f"Ollama request failed: {e}") from e

    return clean_model_output("".join(parts))


# =========================================================
# TEXT CHUNKING + SOURCE SCORING
# =========================================================

def split_text_into_chunks(text: str, max_chars: int = 1600) -> list[str]:
    text = clean_source_text(text)
    if not text:
        return []

    page_blocks = re.split(r"(?=---\s*PAGE\s*\d+\s*---)", text, flags=re.IGNORECASE)
    if len(page_blocks) <= 1:
        page_blocks = re.split(r"\n\s*\n+", text)

    chunks: list[str] = []
    current = ""

    for block in page_blocks:
        block = block.strip()
        if not block:
            continue

        if len(current) + len(block) + 2 <= max_chars:
            current += block + "\n\n"
        else:
            if current.strip():
                chunks.append(current.strip())

            if len(block) > max_chars:
                for i in range(0, len(block), max_chars):
                    part = block[i:i + max_chars].strip()
                    if part:
                        chunks.append(part)
                current = ""
            else:
                current = block + "\n\n"

    if current.strip():
        chunks.append(current.strip())

    return chunks


def words_key(text: str) -> set[str]:
    stop_words = {
        "the", "a", "an", "and", "or", "of", "to", "in", "on", "for", "with",
        "is", "are", "was", "were", "as", "that", "which", "what", "when",
        "does", "do", "from", "into", "by", "it", "they", "them", "this",
        "these", "those", "be", "been", "being", "can", "could", "would",
        "should", "must", "may", "might", "will", "shall", "has", "have",
        "had", "not", "but", "than", "then", "also", "only", "such", "more",
        "most", "less", "between", "among", "through", "about", "their",
        "there", "where", "while", "during", "because", "therefore", "according",
        "page", "slide", "source", "text", "document", "material",
    }

    words = re.findall(r"[a-zA-Z][a-zA-Z0-9_-]+", str(text).lower())
    return {w for w in words if w not in stop_words and len(w) > 2}


def text_similarity(text1: str, text2: str) -> float:
    w1 = words_key(text1)
    w2 = words_key(text2)
    if not w1 or not w2:
        return 0.0
    return len(w1 & w2) / max(1, len(w1 | w2))


def source_support_score(answer_text: str, source_context: str) -> float:
    answer_words = words_key(answer_text)
    source_words = words_key(source_context)
    if not answer_words or not source_words:
        return 0.0
    return len(answer_words & source_words) / max(1, len(answer_words))


def score_context_chunk(chunk: str) -> int:
    low = chunk.lower()
    words = re.findall(r"[a-zA-Z][a-zA-Z0-9_-]+", chunk)
    unique_words = set(w.lower() for w in words)

    score = 0

    if 450 <= len(chunk) <= 1800:
        score += 8
    elif 250 <= len(chunk) < 450:
        score += 4
    elif len(chunk) > 2400:
        score -= 4

    if len(unique_words) >= 50:
        score += 5
    elif len(unique_words) >= 30:
        score += 3

    useful_markers = [
        "definition", "defined as", "refers to", "means", "type", "types",
        "category", "categories", "process", "steps", "stage", "stages",
        "relationship", "related", "compare", "contrast", "difference",
        "cause", "effect", "result", "consequence", "advantage", "disadvantage",
        "benefit", "limitation", "example", "case", "method", "model",
        "concept", "important", "used to", "based on", "consists of",
        "diagram", "event", "response", "flow", "data flow",
    ]

    for marker in useful_markers:
        if marker in low:
            score += 2

    bad_markers = ["table of contents", "references", "bibliography", "copyright", "all rights reserved"]
    for marker in bad_markers:
        if marker in low:
            score -= 8

    symbol_count = len(re.findall(r"[{}|_=<>]", chunk))
    if symbol_count > 25:
        score -= 5

    return score


# =========================================================
# SUMMARY PIPELINE
# =========================================================

def summarize_chunk(chunk: str, index: int, total: int) -> str:
    prompt = f"""
You are a careful academic summarization assistant.

TASK:
Summarize this text section for a student.

RULES:
- Use ONLY the provided text.
- Do NOT use outside knowledge.
- Do NOT invent facts, dates, names, examples, definitions, or explanations.
- Preserve important terms exactly.
- Keep the answer in English.
- Make it useful for studying and exam revision.
- Be concise but complete.

OUTPUT FORMAT:
### Main Ideas
- ...

### Key Facts and Concepts
- ...

### Important Details
- ...

### Exam Revision Notes
- ...

TEXT SECTION {index} OF {total}:
{chunk}
"""

    return call_ollama_generate(
        prompt=prompt,
        model=SUMMARY_MODEL,
        format_json=False,
        timeout=600,
        num_ctx=3072,
        num_predict=900,
        temperature=0.1,
        top_p=0.85,
        repeat_penalty=1.10,
    )


def combine_summaries(summaries: list[str]) -> str:
    if not summaries:
        return "No summary could be generated."

    if len(summaries) == 1:
        return summaries[0]

    joined = "\n\n".join(summaries)

    prompt = f"""
You are a careful academic summarization assistant.

TASK:
Combine the section summaries into one clean study summary.

RULES:
- Use ONLY the section summaries.
- Do NOT use outside knowledge.
- Do NOT invent new facts.
- Remove repetition.
- Keep the answer in English.
- Make it useful for exam revision.

FINAL OUTPUT FORMAT:
# Text Summary

## 1. Main Idea
Write 2-3 sentences.

## 2. Main Topics
- ...

## 3. Key Facts and Concepts
- ...

## 4. Important Details
- ...

## 5. Exam Revision Points
- ...

## 6. Short Final Summary
Write one short paragraph.

SECTION SUMMARIES:
{joined}
"""

    return call_ollama_generate(
        prompt=prompt,
        model=SUMMARY_MODEL,
        format_json=False,
        timeout=600,
        num_ctx=4096,
        num_predict=1200,
        temperature=0.1,
        top_p=0.85,
        repeat_penalty=1.10,
    )


def summarize_uploaded_text(text: str) -> str:
    text = clean_source_text(text)

    if len(text) < 20:
        return "Please enter enough text to summarize."

    if len(text) <= 3000:
        max_chars = SUMMARY_CHUNK_CHARS_SMALL
    elif len(text) <= 9000:
        max_chars = SUMMARY_CHUNK_CHARS_MEDIUM
    else:
        max_chars = SUMMARY_CHUNK_CHARS_LARGE

    chunks = split_text_into_chunks(text, max_chars=max_chars)

    if not chunks:
        return "Please enter enough text to summarize."

    partial_summaries: list[str] = []
    for index, chunk in enumerate(chunks, start=1):
        logger.info(f"Summarizing chunk {index}/{len(chunks)}")
        partial_summaries.append(summarize_chunk(chunk, index, len(chunks)))

    return combine_summaries(partial_summaries)


# =========================================================
# NLP-GUIDED QUIZ CONTEXT
# =========================================================

def split_lines_with_pages(text: str) -> list[dict]:
    text = clean_source_text(text)
    rows: list[dict] = []
    current_page: Optional[str] = None

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        page_match = re.fullmatch(r"---\s*PAGE\s*(\d+)\s*---", line, flags=re.IGNORECASE)
        if page_match:
            current_page = page_match.group(1)
            continue

        cleaned = clean_quiz_part(line)
        if 20 <= len(cleaned) <= 280:
            rows.append({"page": current_page, "text": cleaned, "low": cleaned.lower()})

    return rows


def infer_seed_type(line: str) -> tuple[Optional[str], int]:
    low = line.lower()
    score = 0
    seed_type: Optional[str] = None

    comparison_markers = [
        "differ", "different", "compare", "compared", "contrast", "whereas", "while", "unlike", "similar", "versus",
    ]
    relation_markers = [
        "relationship", "relates to", "related to", "connected to", "depends on", "leads to", "results in",
        "because", "therefore", "cause", "effect", "consequence", "used to", "based on", "consists of",
        "creates", "produces", "requires", "must have", "response",
    ]
    process_markers = [
        "first", "next", "then", "after", "before", "step", "process", "merge", "split", "partition",
        "sequence", "create", "draw", "establish", "define", "develop", "list",
    ]
    concept_markers = [
        "definition", "defined as", "refers to", "means", "type", "types", "category", "model", "method",
        "diagram", "data flow", "system", "subsystem", "event", "store", "entity",
    ]

    if any(m in low for m in comparison_markers):
        seed_type = "comparison"
        score += 14
    if any(m in low for m in relation_markers):
        seed_type = seed_type or "relationship"
        score += 12
    if any(m in low for m in process_markers):
        seed_type = seed_type or "process"
        score += 10
    if any(m in low for m in concept_markers):
        seed_type = seed_type or "concept"
        score += 6
    if re.match(r"^\d+\s*[\.)]?\s*[A-Za-z]", line):
        seed_type = "process_step"
        score += 12
    if len(line.split()) >= 6:
        score += 2

    return seed_type, score


def extract_nlp_question_seeds(text: str, max_seeds: int = 16) -> list[dict]:
    rows = split_lines_with_pages(text)
    seeds: list[dict] = []

    for row in rows:
        seed_type, score = infer_seed_type(row["text"])
        if not seed_type:
            continue
        seeds.append({
            "type": seed_type,
            "page": row["page"],
            "text": row["text"],
            "score": score,
        })

    seeds.sort(key=lambda x: x["score"], reverse=True)

    unique: list[dict] = []
    for seed in seeds:
        if any(text_similarity(seed["text"], old["text"]) >= 0.72 for old in unique):
            continue
        unique.append(seed)
        if len(unique) >= max_seeds:
            break

    return unique


def select_quiz_context_from_seeds(text: str, seeds: list[dict], max_chars: int = QUIZ_MAX_CONTEXT_CHARS) -> str:
    chunks = split_text_into_chunks(text, max_chars=1800)

    seed_words: set[str] = set()
    for seed in seeds:
        seed_words |= words_key(seed.get("text", ""))

    scored_chunks: list[tuple[int, int, str]] = []
    for index, chunk in enumerate(chunks):
        score = score_context_chunk(chunk)
        chunk_words = words_key(chunk)
        if seed_words and chunk_words:
            score += int(20 * (len(seed_words & chunk_words) / max(1, len(seed_words))))
        scored_chunks.append((score, index, chunk))

    scored_chunks.sort(key=lambda x: x[0], reverse=True)

    seed_text = "\n".join(
        f"- Type: {s['type']} | Page: {s['page'] or 'unknown'} | Text: {s['text']}"
        for s in seeds[:10]
    )

    selected_parts = ["QUESTION SEEDS:\n" + (seed_text if seed_text else "No strong seeds found.")]
    total = len(selected_parts[0])

    for score, index, chunk in scored_chunks:
        if total + len(chunk) + 20 > max_chars:
            continue
        selected_parts.append(f"\nSOURCE CHUNK {index + 1}:\n{chunk}")
        total += len(chunk) + 20
        if total >= max_chars:
            break

    return "\n\n".join(selected_parts)[:max_chars]


def retrieve_quiz_context(text: str, difficulty: str = "Mixed", max_chars: int = QUIZ_MAX_CONTEXT_CHARS) -> str:
    """
    Local fallback retriever.
    This replaces app.rag_retriever dependency so this file works alone.
    It does NOT generate questions. It only picks useful source context.
    """
    seeds = extract_nlp_question_seeds(text, max_seeds=10)
    return select_quiz_context_from_seeds(text=text, seeds=seeds, max_chars=max_chars)


# =========================================================
# MCQ PARSING + QUALITY CONTROL
# =========================================================

def get_answer_text(correct_letter: str, a: str, b: str, c: str, d: str) -> str:
    return {"A": a, "B": b, "C": c, "D": d}.get((correct_letter or "").upper(), "")


def normalize_correct_answer(value: str) -> str:
    value = clean_quiz_part(value).upper()
    if value in ["A", "B", "C", "D"]:
        return value
    match = re.search(r"\b([ABCD])\b", value)
    if match:
        return match.group(1)
    return ""


def extract_question_items_from_broken_json(raw_output: str) -> list[dict]:
    raw_output = clean_model_output(raw_output)

    q_pos = raw_output.find('"questions"')
    if q_pos == -1:
        q_pos = raw_output.find("'questions'")
    if q_pos != -1:
        raw_output = raw_output[q_pos:]

    objects: list[str] = []
    start: Optional[int] = None
    depth = 0
    in_string = False
    escape = False

    for i, ch in enumerate(raw_output):
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_string = False
            continue

        if ch == '"':
            in_string = True
            continue
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    objects.append(raw_output[start:i + 1])
                    start = None

    items: list[dict] = []
    for obj in objects:
        if '"question"' not in obj and "'question'" not in obj:
            continue
        cleaned = re.sub(r",\s*}", "}", obj.strip())
        cleaned = re.sub(r",\s*]", "]", cleaned)
        try:
            parsed = json.loads(cleaned)
            if isinstance(parsed, dict):
                items.append(parsed)
        except Exception:
            continue

    return items


def extract_json_from_model_output(raw_output: str) -> Any:
    raw_output = clean_model_output(raw_output)

    try:
        return json.loads(raw_output)
    except Exception:
        pass

    object_match = re.search(r"\{.*\}", raw_output, flags=re.DOTALL)
    if object_match:
        try:
            return json.loads(object_match.group(0))
        except Exception:
            pass

    array_match = re.search(r"\[.*\]", raw_output, flags=re.DOTALL)
    if array_match:
        try:
            return json.loads(array_match.group(0))
        except Exception:
            pass

    salvaged = extract_question_items_from_broken_json(raw_output)
    if salvaged:
        return {"questions": salvaged}

    return None


def contains_bad_source_reference(text: str) -> bool:
    low = clean_quiz_part(text).lower()
    bad_parts = [
        "not explicitly stated", "not stated", "not enough information", "the source does not mention",
        "the document does not say", "implied by the source",
    ]
    return any(part in low for part in bad_parts)


def is_numeric_order_option(text: str) -> bool:
    text = clean_quiz_part(text)
    return bool(re.fullmatch(r"[0-9,\s\-]+", text))


def has_bad_option(options: list[str]) -> bool:
    bad_option_parts = [
        "all of the above", "none of the above", "both a and b", "both a & b", "both are correct",
        "neither a nor b", "neither are correct", "neither", "not enough information",
        "not supported by the source", "invalid option", "unrelated idea", "the system crashes",
        "the document does not say",
    ]

    for option in options:
        low = option.lower()
        if any(part in low for part in bad_option_parts):
            return True
        if is_numeric_order_option(option):
            return True
    return False


def has_partial_correct_option(correct_text: str, wrong_options: list[str]) -> bool:
    correct_words = words_key(correct_text)
    if not correct_words:
        return False

    for option in wrong_options:
        option_words = words_key(option)
        if len(option_words) < 2:
            continue
        overlap = len(option_words & correct_words) / max(1, len(option_words))
        if overlap >= 0.88:
            return True

    return False


def answer_explanation_overlap(correct_text: str, explanation: str) -> float:
    correct_words = words_key(correct_text)
    explanation_words = words_key(explanation)
    if not correct_words or not explanation_words:
        return 0.0
    return len(correct_words & explanation_words) / max(1, len(correct_words))


def find_best_page_for_answer(correct_text: str, source_context: str) -> Optional[str]:
    best_page = None
    best_score = 0.0
    current_page = None

    for raw_line in str(source_context or "").splitlines():
        line = raw_line.strip()
        if not line:
            continue

        seed_page = re.search(r"\bPage:\s*(\d+)\b", line, flags=re.IGNORECASE)
        if seed_page:
            page = seed_page.group(1)
            score = source_support_score(correct_text, line)
            if score > best_score:
                best_score = score
                best_page = page
            continue

        marker = re.fullmatch(r"---\s*PAGE\s*(\d+)\s*---", line, flags=re.IGNORECASE)
        if marker:
            current_page = marker.group(1)
            continue

        if current_page:
            score = source_support_score(correct_text, line)
            if score > best_score:
                best_score = score
                best_page = current_page

    if best_score >= 0.20:
        return best_page
    return None


def normalize_explanation_for_answer(correct_text: str, explanation: str, source_context: str) -> str:
    explanation = clean_quiz_part(explanation)
    correct_text = clean_quiz_part(correct_text)

    if not correct_text:
        return explanation or "The correct answer is supported by the source material."

    overlap = answer_explanation_overlap(correct_text, explanation)
    if explanation and overlap >= 0.28 and not contains_bad_source_reference(explanation):
        return explanation

    page = find_best_page_for_answer(correct_text, source_context)
    if page:
        return f"According to page {page}, {correct_text}."
    return f"According to the source material, {correct_text}."


def is_weak_hard_question(question: str) -> bool:
    q = clean_quiz_part(question).lower()
    weak_patterns = [
        "what is the purpose", "what purpose", "main purpose", "primary purpose",
        "which diagram is used", "which type of data flow", "which type of", "what type of",
        "which diagram", "what diagram", "what is a ", "what is an ", "what are ",
    ]
    if any(pattern in q for pattern in weak_patterns):
        return True
    weak_starts = ["what is ", "what are ", "which type ", "what type ", "which diagram "]
    return any(q.startswith(start) for start in weak_starts)


def infer_question_kind(question: str) -> str:
    q = clean_quiz_part(question).lower()

    if any(x in q for x in ["differ", "different", "compare", "compares", "contrast", "whereas", "while"]):
        return "comparison"
    if any(x in q for x in ["relationship", "relate", "relates", "connection", "connected", "best explains"]):
        return "relationship"
    if any(x in q for x in ["sequence", "order", "progression", "step", "after", "before"]):
        return "sequence"
    if any(x in q for x in ["cause", "effect", "consequence", "result", "leads to", "follows"]):
        return "cause_effect"
    if any(x in q for x in ["apply", "scenario", "best fits", "most likely"]):
        return "application"
    if any(x in q for x in ["best explanation", "best describes", "best accounts", "most accurate"]):
        return "best_explanation"
    return "understanding"


def is_advanced_style_question(question: str) -> bool:
    if is_weak_hard_question(question):
        return False
    return infer_question_kind(question) in [
        "comparison", "relationship", "sequence", "cause_effect", "application", "best_explanation",
    ]


def is_relation_or_comparison_question(question: str) -> bool:
    return infer_question_kind(question) in ["comparison", "relationship", "cause_effect", "best_explanation"]


def question_quality_score(question: str, correct_text: str, explanation: str, support: float) -> int:
    q = clean_quiz_part(question).lower()
    kind = infer_question_kind(question)
    score = 0

    if kind in ["comparison", "relationship", "sequence", "cause_effect", "application", "best_explanation"]:
        score += 10
    if is_relation_or_comparison_question(question):
        score += 8
    if "best explains" in q or "best describes" in q or "best explanation" in q or "most accurate" in q:
        score += 5
    if "differ" in q or "compare" in q or "relationship" in q:
        score += 5
    if support >= 0.45:
        score += 5
    elif support >= 0.30:
        score += 3
    elif support >= 0.12:
        score += 1
    if len(question.split()) >= 8:
        score += 2
    if len(correct_text.split()) >= 4:
        score += 2
    if len(explanation.split()) >= 8:
        score += 2
    if is_weak_hard_question(question):
        score -= 12
    if contains_bad_source_reference(f"{question} {correct_text} {explanation}"):
        score -= 15
    if len(question) < 22:
        score -= 4

    return score


def concept_fingerprint(text: str) -> set[str]:
    words = words_key(text)
    focused = {w for w in words if len(w) >= 6}
    return focused if focused else words


def concept_overlap(text1: str, text2: str) -> float:
    f1 = concept_fingerprint(text1)
    f2 = concept_fingerprint(text2)
    if not f1 or not f2:
        return 0.0
    return len(f1 & f2) / max(1, min(len(f1), len(f2)))


def is_duplicate_question(new_q: QuizQuestion, existing: list[QuizQuestion]) -> bool:
    new_answer = clean_quiz_part(new_q.correct_answer_text)
    new_explanation = clean_quiz_part(new_q.explanation)

    for old in existing:
        old_answer = clean_quiz_part(old.correct_answer_text)
        old_explanation = clean_quiz_part(old.explanation)

        q_sim = text_similarity(new_q.question, old.question)
        ans_sim = text_similarity(new_answer, old_answer)
        exp_sim = text_similarity(new_explanation, old_explanation)

        if q_sim >= 0.84:
            return True
        if ans_sim >= 0.88:
            return True
        if exp_sim >= 0.90:
            return True
        if concept_overlap(new_answer, old_answer) >= 0.86:
            return True
        if concept_overlap(new_explanation, old_explanation) >= 0.88:
            return True
        if q_sim >= 0.62 and ans_sim >= 0.62:
            return True

    return False


def parse_quiz_json(raw_output: str, source_context: str, limit: int, strict: bool = True) -> list[tuple[int, QuizQuestion]]:
    data = extract_json_from_model_output(raw_output)
    if data is None:
        return []

    if isinstance(data, dict):
        items = data.get("questions", [])
    elif isinstance(data, list):
        items = data
    else:
        return []

    if not isinstance(items, list):
        return []

    candidates: list[tuple[int, QuizQuestion]] = []

    for item in items:
        if not isinstance(item, dict):
            continue

        question = clean_quiz_part(item.get("question", ""))
        a = clean_quiz_part(item.get("option_a", item.get("A", "")))
        b = clean_quiz_part(item.get("option_b", item.get("B", "")))
        c = clean_quiz_part(item.get("option_c", item.get("C", "")))
        d = clean_quiz_part(item.get("option_d", item.get("D", "")))

        correct = normalize_correct_answer(
            item.get("correct_answer", item.get("correct", item.get("answer", item.get("correct_option", ""))))
        )
        explanation = clean_quiz_part(item.get("explanation", ""))

        if not question or not a or not b or not c or not d:
            continue
        if len(question) < 18:
            continue
        if correct not in ["A", "B", "C", "D"]:
            continue

        options = [a, b, c, d]
        if len({opt.lower() for opt in options}) < 4:
            continue
        if has_bad_option(options):
            continue

        correct_text = get_answer_text(correct, a, b, c, d)
        if not correct_text:
            continue

        wrong_options = [opt for opt in options if opt.lower() != correct_text.lower()]
        if has_partial_correct_option(correct_text, wrong_options):
            continue

        if contains_bad_source_reference(f"{question} {correct_text} {explanation}"):
            continue

        support = source_support_score(correct_text, source_context)
        if strict and support < 0.03:
            continue

        explanation = normalize_explanation_for_answer(correct_text, explanation, source_context)

        quiz_question = QuizQuestion(
            question=question,
            option_a=a,
            option_b=b,
            option_c=c,
            option_d=d,
            correct_answer=correct,
            correct_answer_text=correct_text,
            explanation=explanation,
        )

        score = question_quality_score(question, correct_text, explanation, support)
        candidates.append((score, quiz_question))

    candidates.sort(key=lambda item: item[0], reverse=True)
    return candidates[:limit]


def select_final_mixed_questions(candidates: list[tuple[int, QuizQuestion]], requested_questions: int) -> list[QuizQuestion]:
    hard_target = 3 if requested_questions >= 5 else max(1, round(requested_questions * 0.6))
    selected: list[QuizQuestion] = []

    hard_candidates = [(score, q) for score, q in candidates if is_advanced_style_question(q.question)]
    other_candidates = [(score, q) for score, q in candidates if not is_advanced_style_question(q.question)]

    for score, q in hard_candidates:
        if len([x for x in selected if is_advanced_style_question(x.question)]) >= hard_target:
            break
        if not is_duplicate_question(q, selected):
            selected.append(q)

    for score, q in other_candidates + hard_candidates:
        if len(selected) >= requested_questions:
            break
        if not is_duplicate_question(q, selected):
            selected.append(q)

    # Last-resort: return 5 instead of dropping to 3 if duplicate filter was too strict.
    for score, q in candidates:
        if len(selected) >= requested_questions:
            break
        selected.append(q)

    return selected[:requested_questions]


# =========================================================
# MCQ GENERATION PROMPTS
# =========================================================

def build_nlp_guided_quiz_prompt(context: str, requested_questions: int, difficulty: str) -> str:
    difficulty = normalize_difficulty(difficulty)

    if difficulty == "Mixed":
        hard_count = 3 if requested_questions >= 5 else max(1, round(requested_questions * 0.6))
        difficulty_block = f"""
MIXED QUIZ REQUIREMENT:
- Return EXACTLY {requested_questions} final MCQs, not candidates.
- Questions 1 to {hard_count} MUST be HARD / ADVANCED-STYLE.
- Questions {hard_count + 1} to {requested_questions} MUST be MEDIUM-STYLE.
- For 5 questions, this means exactly 3 hard-style questions and exactly 2 medium-style questions.
- Hard / advanced-style means comparison, relationship, cause/effect, sequence, process logic, consequence, scenario, or best-explanation.
- Medium-style means clear understanding questions that are more direct but still useful.
"""
    elif difficulty == "Hard":
        difficulty_block = f"""
HARD QUIZ REQUIREMENT:
- Return EXACTLY {requested_questions} final MCQs, not candidates.
- Every question should be exam-style.
- Prefer comparison, relationship, cause/effect, sequence, consequence, process logic, scenario, or best-explanation.
- Avoid simple recall.
"""
    else:
        difficulty_block = f"""
MEDIUM QUIZ REQUIREMENT:
- Return EXACTLY {requested_questions} final MCQs, not candidates.
- Questions should test understanding from the text.
- They may be direct but should not be silly, trivial, or unrelated.
"""

    return f"""
You are a strict university professor creating multiple-choice exam questions.

TASK:
Generate the FINAL MCQ quiz from the provided SOURCE MATERIAL.
Do NOT generate extra candidate questions.

{difficulty_block}

SOURCE RULES:
- The QUESTION SEEDS are selected by an NLP preprocessor.
- They are NOT questions.
- Use them as source-backed material for stronger questions.
- Prefer the seeds for hard questions.
- Use ONLY the provided source material.
- Do NOT use outside knowledge.
- Do NOT invent facts, examples, benefits, labels, or explanations.

FORBIDDEN FOR HARD QUESTIONS:
- Do NOT ask "What is the purpose of ...?"
- Do NOT ask "Which diagram is used ...?"
- Do NOT ask "Which type of data flow ...?"
- Do NOT ask simple definition questions.
- Do NOT copy a numbered bullet and turn it into a recall question.

GOOD HARD QUESTION STARTERS:
- "Which statement best explains the relationship between X and Y...?"
- "How does X differ from Y...?"
- "Which consequence follows when...?"
- "Which option best explains why X leads to Y...?"
- "Which statement best describes how X relates to Y...?"
- "Which option best compares X and Y...?"

OPTIONS:
- Every question must have exactly 4 options: A, B, C, D.
- Only ONE option must be correct.
- Wrong options must be believable and related to the same topic.
- Do NOT use "all of the above", "none of the above", "both A and B", or "neither A nor B".
- Keep options similar in length.

EXPLANATION:
- The explanation MUST justify the selected correct_answer.
- The explanation MUST contain the same main concept as the correct option.
- If page markers exist, explanations may mention the correct page.
- Do NOT invent page numbers.

OUTPUT:
Return valid JSON only. No markdown. No text before or after JSON. No trailing commas.

JSON shape:
{{
  "questions": [
    {{
      "question": "Question text?",
      "option_a": "Option A",
      "option_b": "Option B",
      "option_c": "Option C",
      "option_d": "Option D",
      "correct_answer": "A",
      "explanation": "According to page X, short explanation based only on the source material."
    }}
  ]
}}

SOURCE MATERIAL:
{context}
""".strip()


def build_failure_repair_prompt(raw_output: str, context: str, requested_questions: int, difficulty: str) -> str:
    difficulty = normalize_difficulty(difficulty)

    if difficulty == "Mixed":
        difficulty_rules = """
MIXED REQUIREMENT:
- Return EXACTLY 5 MCQs.
- Questions 1, 2, and 3 should be advanced-style when possible.
- Questions 4 and 5 should be medium-style.
"""
    elif difficulty == "Hard":
        difficulty_rules = """
HARD REQUIREMENT:
- Return exam-style MCQs.
- Prefer comparison, relationship, cause/effect, sequence, consequence, process logic, or best-explanation.
"""
    else:
        difficulty_rules = """
MEDIUM REQUIREMENT:
- Return clear understanding-based MCQs.
"""

    return f"""
You are repairing an MCQ JSON output.

TASK:
The previous model output has draft questions, but it is INVALID.
Repair it into a valid final quiz using ONLY the SOURCE MATERIAL.

{difficulty_rules}

STRICT REPAIR RULES:
- Return EXACTLY {requested_questions} MCQs.
- Every question must include: question, option_a, option_b, option_c, option_d, correct_answer, explanation.
- correct_answer must be exactly one letter: A, B, C, or D.
- Do NOT invent facts, benefits, examples, or page numbers.
- Do NOT add outside knowledge.
- Keep wrong options believable and related.

OUTPUT:
Return valid JSON only.

SOURCE MATERIAL:
{context}

INVALID DRAFT OUTPUT TO REPAIR:
{raw_output[:4500]}
""".strip()


def call_quiz_model(prompt: str) -> str:
    return call_ollama_generate(
        prompt=prompt,
        model=QUIZ_MODEL,
        format_json=True,
        timeout=OLLAMA_TIMEOUT_SECONDS,
        num_ctx=QUIZ_NUM_CTX,
        num_predict=QUIZ_NUM_PREDICT,
        temperature=0.05,
        top_p=0.80,
        repeat_penalty=1.12,
    )


def call_failure_repair_model(prompt: str) -> str:
    return call_ollama_generate(
        prompt=prompt,
        model=QUIZ_MODEL,
        format_json=True,
        timeout=OLLAMA_TIMEOUT_SECONDS,
        num_ctx=QUIZ_NUM_CTX,
        num_predict=1400,
        temperature=0.05,
        top_p=0.82,
        repeat_penalty=1.13,
    )


def generate_quiz_from_text(text: str, number_of_questions: int = 5, difficulty: str = "Medium") -> tuple[list[QuizQuestion], str]:
    text = clean_source_text(text)
    if len(text) < 100:
        return [], "Not enough readable text."

    requested_questions = clamp_question_count(number_of_questions)
    difficulty = normalize_difficulty(difficulty)

    seeds = extract_nlp_question_seeds(text, max_seeds=8)
    context = retrieve_quiz_context(text=text, difficulty=difficulty, max_chars=QUIZ_MAX_CONTEXT_CHARS)

    prompt = build_nlp_guided_quiz_prompt(context=context, requested_questions=requested_questions, difficulty=difficulty)
    raw_output = call_quiz_model(prompt)

    candidates = parse_quiz_json(raw_output=raw_output, source_context=context, limit=requested_questions, strict=True)

    if len(candidates) < requested_questions:
        relaxed = parse_quiz_json(raw_output=raw_output, source_context=context, limit=requested_questions, strict=False)
        merged = candidates[:]
        existing_qs = [q for _, q in merged]
        for score, q in relaxed:
            if len(merged) >= requested_questions:
                break
            if not is_duplicate_question(q, existing_qs):
                merged.append((score, q))
                existing_qs.append(q)
        merged.sort(key=lambda item: item[0], reverse=True)
        candidates = merged[:requested_questions]

    questions = select_final_mixed_questions(candidates=candidates, requested_questions=requested_questions)

    repair_raw_output = ""
    repair_call_used = False

    if len(questions) == 0 and '"questions"' in raw_output:
        repair_prompt = build_failure_repair_prompt(
            raw_output=raw_output,
            context=context,
            requested_questions=requested_questions,
            difficulty=difficulty,
        )
        repair_raw_output = call_failure_repair_model(repair_prompt)
        repair_call_used = True
        repair_candidates = parse_quiz_json(
            raw_output=repair_raw_output,
            source_context=context,
            limit=requested_questions,
            strict=False,
        )
        questions = select_final_mixed_questions(
            candidates=repair_candidates,
            requested_questions=requested_questions,
        )

    final_relation_count = sum(1 for q in questions if is_relation_or_comparison_question(q.question))
    hard_style_count = sum(1 for q in questions if is_advanced_style_question(q.question))

    debug_output = f"""
--- STUDYFLOW PHI4-MINI MCQ QUIZ PIPELINE ---
model: {QUIZ_MODEL}
difficulty: {display_difficulty(difficulty)}
difficulty_internal: {difficulty}
requested_questions: {requested_questions}
context_chars: {len(context)}
seeds_extracted: {len(seeds)}
generated_valid_questions: {len(questions)}
hard_style_questions: {hard_style_count}
relation_or_comparison_questions: {final_relation_count}
llama_is_main_generator: true
nlp_used_for_seed_selection_only: true
rule_based_question_generation: false
repair_call_used: {repair_call_used}
llm_calls: {2 if repair_call_used else 1}
num_ctx: {QUIZ_NUM_CTX}
num_predict: {QUIZ_NUM_PREDICT}
question_kinds: {[infer_question_kind(q.question) for q in questions]}

--- QUESTION SEEDS ---
{json.dumps(seeds, ensure_ascii=False, indent=2)}

--- RAW MODEL OUTPUT ---
{raw_output}

--- REPAIR RAW MODEL OUTPUT ---
{repair_raw_output}
""".strip()

    if len(questions) < requested_questions:
        debug_output += f"\n\n--- QUALITY WARNING ---\nOnly {len(questions)} valid questions were generated out of {requested_questions}."

    return questions[:requested_questions], debug_output


# =========================================================
# WRITTEN QUIZ GENERATION + GRADING
# =========================================================

def strip_page_reference_from_question(question: str) -> str:
    question = clean_quiz_part(question)
    if not question:
        return ""

    question = re.sub(
        r"\s*\((?:according to|as described on|as shown on|based on)\s+page\s+\d+\s*(?:of the source|of the source material)?\)",
        "",
        question,
        flags=re.IGNORECASE,
    )
    question = re.sub(
        r"\s*(?:,?\s*)?(?:according to|as described on|as shown on|based on)\s+page\s+\d+\s*(?:of the source|of the source material)?",
        "",
        question,
        flags=re.IGNORECASE,
    )
    question = re.sub(
        r"\s*(?:,?\s*)?(?:according to|as described in|based on)\s+(?:the\s+)?(?:source|source material)",
        "",
        question,
        flags=re.IGNORECASE,
    )
    question = re.sub(r"\s+", " ", question).strip()
    question = re.sub(r"\s+\?", "?", question).strip()

    if question and not question.endswith("?"):
        question = question.rstrip(" .") + "?"

    return question


def is_weak_written_hard_question(question: str) -> bool:
    q = clean_quiz_part(question).lower()
    weak_patterns = [
        "what is the purpose", "what is the primary purpose", "what is the main purpose", "what purpose",
        "primary purpose", "main purpose", "what is ", "what are ", "define ", "list ", "identify ",
        "which type", "which diagram", "what type", "what does ", "what is meant by",
    ]
    if any(pattern in q for pattern in weak_patterns):
        return True
    weak_starts = ["what is ", "what are ", "define ", "list ", "identify ", "which type ", "what type "]
    return any(q.startswith(start) for start in weak_starts)


def is_strong_written_hard_question(question: str) -> bool:
    if is_weak_written_hard_question(question):
        return False
    q = clean_quiz_part(question).lower()
    strong_markers = [
        "how does", "how do", "why does", "why would", "explain how", "explain why", "analyze",
        "compare", "contrast", "different", "difference", "relationship", "relates", "connected",
        "cause", "effect", "consequence", "what consequence", "what would happen", "why is",
        "in what way", "under what condition", "how would", "how can", "why might",
    ]
    return any(marker in q for marker in strong_markers)


def written_question_quality_score(question: str, expected_answer: str) -> int:
    q = clean_quiz_part(question).lower()
    score = 0

    if is_strong_written_hard_question(question):
        score += 25
    if any(x in q for x in ["relationship", "relates", "connected"]):
        score += 8
    if any(x in q for x in ["compare", "contrast", "different", "difference"]):
        score += 8
    if any(x in q for x in ["cause", "effect", "consequence", "result"]):
        score += 8
    if any(x in q for x in ["how does", "explain how", "why does", "why would"]):
        score += 6
    if len(question.split()) >= 9:
        score += 3
    if len(expected_answer.split()) >= 10:
        score += 3
    if is_weak_written_hard_question(question):
        score -= 20

    return score


def is_duplicate_written_question(new_q: WrittenQuestion, existing: list[WrittenQuestion]) -> bool:
    for old in existing:
        if text_similarity(new_q.question, old.question) >= 0.82:
            return True
        if text_similarity(new_q.expected_answer, old.expected_answer) >= 0.82:
            return True
    return False


def source_fact_rows_with_pages(source_context: str) -> list[dict]:
    text = clean_source_text(source_context)
    rows: list[dict] = []
    current_page: Optional[str] = None
    buffer = ""
    buffer_page: Optional[str] = None

    def flush_buffer() -> None:
        nonlocal buffer, buffer_page
        fact = clean_quiz_part(buffer)
        if 18 <= len(fact) <= 360:
            rows.append({"page": buffer_page, "text": fact})
        buffer = ""
        buffer_page = None

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        page_match = re.fullmatch(r"---\s*PAGE\s*(\d+)\s*---", line, flags=re.IGNORECASE)
        if page_match:
            flush_buffer()
            current_page = page_match.group(1)
            continue

        if line.upper().startswith("QUESTION SEEDS") or line.upper().startswith("SOURCE CHUNK"):
            flush_buffer()
            continue

        cleaned = clean_quiz_part(line)
        if not cleaned:
            continue

        seed_match = re.search(r"\bPage:\s*(\d+|unknown)\s*\|\s*Text:\s*(.+)$", cleaned, flags=re.IGNORECASE)
        if seed_match:
            flush_buffer()
            page = None if seed_match.group(1).lower() == "unknown" else seed_match.group(1)
            fact = clean_quiz_part(seed_match.group(2))
            if 18 <= len(fact) <= 360:
                rows.append({"page": page, "text": fact})
            continue

        starts_numbered_step = bool(re.match(r"^\d+\s*[\.)]\s*", cleaned))
        looks_like_title = len(cleaned.split()) <= 7 and not cleaned.endswith(".") and not starts_numbered_step
        if looks_like_title and not buffer:
            continue

        if starts_numbered_step:
            flush_buffer()
            buffer = cleaned
            buffer_page = current_page
            continue

        if buffer:
            if len(buffer) + len(cleaned) + 1 <= 360 and not starts_numbered_step:
                buffer = f"{buffer} {cleaned}"
            else:
                flush_buffer()
                buffer = cleaned
                buffer_page = current_page
        else:
            buffer = cleaned
            buffer_page = current_page

        if buffer.endswith(".") and len(buffer) >= 35:
            flush_buffer()

    flush_buffer()

    unique: list[dict] = []
    for row in rows:
        if any(text_similarity(row["text"], old["text"]) >= 0.86 for old in unique):
            continue
        unique.append(row)

    return unique


def unsupported_word_ratio(answer: str, source_context: str) -> float:
    answer_words = words_key(answer)
    source_words = words_key(source_context)
    if not answer_words or not source_words:
        return 1.0
    unsupported = answer_words - source_words
    return len(unsupported) / max(1, len(answer_words))


def expected_answer_is_source_safe(answer: str, source_context: str) -> bool:
    answer = clean_quiz_part(answer)
    if not answer:
        return False
    support = source_support_score(answer, source_context)
    unsupported_ratio = unsupported_word_ratio(answer, source_context)
    return support >= 0.42 and unsupported_ratio <= 0.40 and not contains_bad_source_reference(answer)


def find_source_facts_for_question(
    question: str,
    expected_answer: str,
    source_context: str,
    max_facts: int = 2,
) -> tuple[list[dict], float]:
    facts = source_fact_rows_with_pages(source_context)
    if not facts:
        return [], 0.0

    question_words = words_key(question)
    answer_words = words_key(expected_answer)

    scored: list[tuple[float, dict]] = []
    for fact in facts:
        fact_text = fact["text"]
        fact_words = words_key(fact_text)
        if not fact_words:
            continue

        q_overlap = len(question_words & fact_words) / max(1, len(question_words))
        a_overlap = len(answer_words & fact_words) / max(1, len(answer_words)) if answer_words else 0.0
        quality = min(len(fact_text.split()) / 18, 1.0)
        score = (q_overlap * 0.70) + (a_overlap * 0.20) + (quality * 0.10)
        scored.append((score, fact))

    scored.sort(key=lambda item: item[0], reverse=True)

    selected: list[dict] = []
    best_score = scored[0][0] if scored else 0.0
    for score, fact in scored:
        if score < 0.12:
            continue
        if selected and text_similarity(fact["text"], selected[0]["text"]) >= 0.80:
            continue
        selected.append(fact)
        if len(selected) >= max_facts:
            break

    return selected, best_score


def source_ground_written_answer(
    question: str,
    expected_answer: str,
    explanation: str,
    source_context: str,
) -> tuple[str, str, Optional[str], bool]:
    expected_answer = clean_quiz_part(expected_answer)
    explanation = clean_quiz_part(explanation)

    if expected_answer_is_source_safe(expected_answer, source_context):
        page = find_best_page_for_answer(expected_answer, source_context)
        if not explanation or not expected_answer_is_source_safe(explanation, source_context):
            explanation = f"According to page {page}, {expected_answer}" if page else f"According to the source material, {expected_answer}"
        return expected_answer, explanation, page, False

    facts, best_score = find_source_facts_for_question(
        question=question,
        expected_answer=expected_answer,
        source_context=source_context,
        max_facts=2,
    )

    if not facts:
        page = find_best_page_for_answer(expected_answer, source_context)
        explanation = f"According to page {page}, {expected_answer}" if page else f"According to the source material, {expected_answer}"
        return expected_answer, explanation, page, False

    q_low = clean_quiz_part(question).lower()
    wants_two_facts = any(marker in q_low for marker in [
        "differ", "difference", "compare", "relationship", "relate", "relates", "connected", "between",
    ])

    if wants_two_facts and len(facts) >= 2:
        safe_answer = f"{facts[0]['text']} {facts[1]['text']}"
        page = facts[0].get("page") or facts[1].get("page")
    else:
        safe_answer = facts[0]["text"]
        page = facts[0].get("page")

    safe_explanation = f"According to page {page}, {safe_answer}" if page else f"According to the source material, {safe_answer}"
    return safe_answer, safe_explanation, page, True


def build_written_quiz_prompt(context: str, requested_questions: int, difficulty: str) -> str:
    difficulty = normalize_difficulty(difficulty)
    candidate_count = max(requested_questions + 3, 8)

    if difficulty == "Mixed":
        hard_count = 3 if requested_questions >= 5 else max(1, round(requested_questions * 0.6))
        difficulty_block = f"""
MIXED WRITTEN QUIZ REQUIREMENT:
- Generate EXACTLY {candidate_count} candidate written-answer questions.
- At least {hard_count + 2} candidates should be HARD-style questions.
- At least 3 candidates should be MEDIUM-style questions.
- The backend will select exactly {requested_questions} final questions.
- For 5 final questions, the backend will display exactly 3 Hard and exactly 2 Medium.
"""
    elif difficulty == "Hard":
        difficulty_block = f"""
HARD WRITTEN QUIZ REQUIREMENT:
- Generate EXACTLY {candidate_count} candidate written-answer questions.
- Every question should require reasoning.
- Prefer comparison, relationship, sequence, process logic, consequence, or explanation.
"""
    else:
        difficulty_block = f"""
MEDIUM WRITTEN QUIZ REQUIREMENT:
- Generate EXACTLY {candidate_count} candidate written-answer questions.
- Questions should test clear understanding from the source.
"""

    return f"""
You are a strict university professor creating written-answer exam questions.

TASK:
Generate candidate written-answer questions from the SOURCE MATERIAL.
Do NOT generate MCQ options.

{difficulty_block}

SOURCE DISCIPLINE:
- Use ONLY the SOURCE MATERIAL.
- Do NOT use outside knowledge.
- Do NOT invent facts, examples, page numbers, benefits, labels, or explanations.
- Do NOT force a relationship between two concepts unless that relationship is clearly supported.
- If the source only lists steps, ask about the step, sequence, or stated role of the step.
- Do NOT mention page numbers inside the question text.
- Put page numbers only in the JSON field "page".
- The visible question must make sense without referring to a page number.

FORBIDDEN FOR HARD QUESTIONS:
- Do NOT ask "What is the purpose of ...?"
- Do NOT ask "What is ...?"
- Do NOT ask "Define ...?"
- Do NOT ask simple identification questions.

GOOD HARD WRITTEN QUESTION STARTERS:
- "How does X differ from Y?"
- "How does step X support step Y in the source process?"
- "What consequence follows when X happens?"
- "Explain how X is used to Y."
- "How are X and Y connected in the source material?"
- "Why is X necessary before Y?"

FOR EACH QUESTION:
- question: the question shown to the student.
- difficulty: exactly "Hard" or "Medium".
- expected_answer: a short conservative 1-2 sentence answer using only source-supported facts.
- keywords: 4 to 8 important terms/phrases from the expected answer.
- grading_points: 2 to 4 short source-supported facts from the expected answer.
- page: page number as string if known, otherwise null.
- explanation: short explanation based only on source material.

OUTPUT:
Return valid JSON only. No markdown. No text before or after JSON. No trailing commas.

JSON shape:
{{
  "questions": [
    {{
      "question": "Question text?",
      "difficulty": "Hard",
      "expected_answer": "Short model answer based only on the source.",
      "keywords": ["term one", "term two"],
      "grading_points": ["fact one", "fact two"],
      "page": "5",
      "explanation": "Short source-grounded explanation."
    }}
  ]
}}

SOURCE MATERIAL:
{context}
""".strip()


def call_written_quiz_model(prompt: str) -> str:
    return call_ollama_generate(
        prompt=prompt,
        model=QUIZ_MODEL,
        format_json=True,
        timeout=OLLAMA_TIMEOUT_SECONDS,
        num_ctx=QUIZ_NUM_CTX,
        num_predict=1450,
        temperature=0.05,
        top_p=0.80,
        repeat_penalty=1.12,
    )


def parse_written_candidates_json(raw_output: str, source_context: str) -> list[tuple[int, WrittenQuestion]]:
    data = extract_json_from_model_output(raw_output)
    if data is None:
        return []

    if isinstance(data, dict):
        items = data.get("questions", [])
    elif isinstance(data, list):
        items = data
    else:
        return []

    if not isinstance(items, list):
        return []

    candidates: list[tuple[int, WrittenQuestion]] = []

    for item in items:
        if not isinstance(item, dict):
            continue

        question = strip_page_reference_from_question(item.get("question", ""))
        expected_answer = clean_quiz_part(item.get("expected_answer", item.get("answer", "")))
        explanation = clean_quiz_part(item.get("explanation", ""))

        if not question or not expected_answer:
            continue

        expected_answer, explanation, safe_page, answer_was_source_rewritten = source_ground_written_answer(
            question=question,
            expected_answer=expected_answer,
            explanation=explanation,
            source_context=source_context,
        )

        raw_diff = clean_quiz_part(item.get("difficulty", ""))
        diff = "Hard" if raw_diff.lower() == "hard" else "Medium"

        page_value = item.get("page", None)
        if safe_page:
            page = safe_page
        elif page_value is not None:
            page = clean_quiz_part(page_value)
            if page.lower() in ["none", "null", "unknown", ""]:
                page = None
        else:
            page = find_best_page_for_answer(expected_answer, source_context)

        if not explanation:
            explanation = f"According to page {page}, {expected_answer}" if page else f"According to the source material, {expected_answer}"

        written_q = WrittenQuestion(
            question=question,
            difficulty=diff,
            expected_answer=expected_answer,
            keywords=[],
            grading_points=[],
            page=page,
            explanation=explanation,
        )

        score = written_question_quality_score(question, expected_answer)
        q_support = source_support_score(question, source_context)
        score += int(q_support * 12)
        if q_support < 0.18:
            score -= 8
        if re.search(r"\bpage\s+\d+\b", question, flags=re.IGNORECASE):
            score -= 10
        if answer_was_source_rewritten:
            score += 2

        candidates.append((score, written_q))

    candidates.sort(key=lambda item: item[0], reverse=True)
    return candidates


def select_written_questions(candidates: list[tuple[int, WrittenQuestion]], requested_questions: int, difficulty: str) -> list[WrittenQuestion]:
    difficulty = normalize_difficulty(difficulty)
    if not candidates:
        return []

    requested_questions = clamp_question_count(requested_questions)

    if difficulty == "Mixed":
        hard_target = 3 if requested_questions >= 5 else max(1, round(requested_questions * 0.6))
    elif difficulty == "Hard":
        hard_target = requested_questions
    else:
        hard_target = 0

    selected: list[WrittenQuestion] = []
    sorted_candidates = sorted(candidates, key=lambda item: item[0], reverse=True)
    hard_candidates = [(score, q) for score, q in sorted_candidates if is_strong_written_hard_question(q.question)]
    other_candidates = [(score, q) for score, q in sorted_candidates if not is_strong_written_hard_question(q.question)]

    def add_question(q: WrittenQuestion, force_difficulty: Optional[str] = None, allow_duplicate: bool = False) -> bool:
        if len(selected) >= requested_questions:
            return False
        if not allow_duplicate and is_duplicate_written_question(q, selected):
            return False
        q.difficulty = force_difficulty or q.difficulty
        selected.append(q)
        return True

    if difficulty == "Mixed":
        for score, q in hard_candidates:
            if len([x for x in selected if x.difficulty == "Hard"]) >= hard_target:
                break
            add_question(q, force_difficulty="Hard")

        for score, q in sorted_candidates:
            if len([x for x in selected if x.difficulty == "Hard"]) >= hard_target:
                break
            add_question(q, force_difficulty="Hard")

        for score, q in other_candidates + hard_candidates:
            if len(selected) >= requested_questions:
                break
            add_question(q, force_difficulty="Medium")

        for score, q in sorted_candidates:
            if len(selected) >= requested_questions:
                break
            add_question(q, force_difficulty="Medium", allow_duplicate=True)

        final_questions = selected[:requested_questions]
        for index, q in enumerate(final_questions, start=1):
            q.difficulty = "Hard" if index <= hard_target else "Medium"
        return final_questions

    if difficulty == "Hard":
        for score, q in hard_candidates + other_candidates:
            if len(selected) >= requested_questions:
                break
            add_question(q, force_difficulty="Hard")
        for score, q in sorted_candidates:
            if len(selected) >= requested_questions:
                break
            add_question(q, force_difficulty="Hard", allow_duplicate=True)
        return selected[:requested_questions]

    for score, q in other_candidates + hard_candidates:
        if len(selected) >= requested_questions:
            break
        add_question(q, force_difficulty="Medium")

    for score, q in sorted_candidates:
        if len(selected) >= requested_questions:
            break
        add_question(q, force_difficulty="Medium", allow_duplicate=True)

    return selected[:requested_questions]


def generate_written_quiz_from_text(text: str, number_of_questions: int = 5, difficulty: str = "Mixed") -> tuple[list[WrittenQuestion], str]:
    text = clean_source_text(text)
    if len(text) < 100:
        return [], "Not enough readable text."

    requested_questions = clamp_question_count(number_of_questions)
    difficulty = normalize_difficulty(difficulty)

    seeds = extract_nlp_question_seeds(text, max_seeds=8)
    seed_context = select_quiz_context_from_seeds(text=text, seeds=seeds, max_chars=QUIZ_MAX_CONTEXT_CHARS)
    rag_context = retrieve_quiz_context(text=text, difficulty=difficulty, max_chars=QUIZ_MAX_CONTEXT_CHARS)
    context = (seed_context + "\n\n" + rag_context).strip()[:QUIZ_MAX_CONTEXT_CHARS]

    prompt = build_written_quiz_prompt(context=context, requested_questions=requested_questions, difficulty=difficulty)
    raw_output = call_written_quiz_model(prompt)

    candidates = parse_written_candidates_json(raw_output, context)
    questions = select_written_questions(candidates=candidates, requested_questions=requested_questions, difficulty=difficulty)

    hard_target = 3 if requested_questions >= 5 else max(1, round(requested_questions * 0.6))
    strong_hard_count = sum(1 for q in questions if q.difficulty == "Hard" and is_strong_written_hard_question(q.question))

    debug_output = f"""
--- STUDYFLOW PHI4-MINI WRITTEN QUIZ PIPELINE ---
model: {QUIZ_MODEL}
difficulty: {display_difficulty(difficulty)}
requested_questions: {requested_questions}
generated_valid_questions: {len(questions)}
strong_hard_questions: {strong_hard_count}
context_chars: {len(context)}
seeds_extracted: {len(seeds)}
llm_calls: 1
local_grading_after_submit: true
sentence_by_sentence_feedback: true
mixed_layout_exact_3_hard_2_medium: true
rule_based_question_generation: false
source_grounded_expected_answers: true
keyword_grading_used: false
grading_points_used: false
grading_basis: expected_answer_plus_explanation

--- FINAL QUESTION TYPES ---
{json.dumps([{"difficulty": q.difficulty, "question": q.question} for q in questions], ensure_ascii=False, indent=2)}

--- QUESTION SEEDS ---
{json.dumps(seeds, ensure_ascii=False, indent=2)}

--- RAW MODEL OUTPUT ---
{raw_output}
""".strip()

    if len(questions) < requested_questions:
        debug_output += f"\n\n--- QUALITY WARNING ---\nOnly {len(questions)} valid written questions were generated out of {requested_questions}."

    if difficulty == "Mixed" and strong_hard_count < hard_target:
        debug_output += f"\n\n--- MIXED QUALITY NOTE ---\nOnly {strong_hard_count} strong Hard-style questions were found. The layout is still returned as 3 Hard + 2 Medium."

    return questions[:requested_questions], debug_output


# =========================================================
# WRITTEN ANSWER GRADING
# =========================================================

def normalize_match_text(text: str) -> str:
    text = clean_quiz_part(text).lower()
    text = re.sub(r"[^a-z0-9\s\-_/]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def term_match_score(term: str, answer_text: str) -> float:
    term_norm = normalize_match_text(term)
    answer_norm = normalize_match_text(answer_text)

    if not term_norm or not answer_norm:
        return 0.0
    if term_norm in answer_norm:
        return 1.0

    term_words = words_key(term_norm)
    answer_words = words_key(answer_norm)
    if not term_words or not answer_words:
        return 0.0
    return len(term_words & answer_words) / max(1, len(term_words))


def split_user_sentences(answer: str) -> list[str]:
    answer = clean_quiz_part(answer)
    if not answer:
        return []
    parts = re.split(r"(?<=[.!?])\s+|\n+", answer)
    sentences = [clean_quiz_part(part) for part in parts if clean_quiz_part(part)]
    return sentences or [answer]


def sentence_correctness(sentence: str, expected_answer: str, explanation: str) -> SentenceFeedback:
    expected_similarity = text_similarity(sentence, expected_answer)
    expected_support = source_support_score(sentence, expected_answer)
    explanation_similarity = text_similarity(sentence, explanation) if explanation else 0.0
    explanation_support = source_support_score(sentence, explanation) if explanation else 0.0

    confidence = max(expected_similarity, expected_support, explanation_similarity, explanation_support)
    is_correct = expected_similarity >= 0.18 or expected_support >= 0.35 or explanation_similarity >= 0.18 or explanation_support >= 0.35

    return SentenceFeedback(
        sentence=sentence,
        is_correct=is_correct,
        confidence=round(float(min(confidence, 1.0)), 2),
        matched_keywords=[],
        comment="Supported by the expected answer." if is_correct else "Not clearly supported by the expected answer. Check this sentence.",
    )


def grade_one_written_answer(item: WrittenUserAnswer) -> WrittenAnswerGrade:
    user_answer = clean_quiz_part(item.user_answer)
    expected_answer = clean_quiz_part(item.expected_answer)
    explanation = clean_quiz_part(item.explanation or "")

    if not user_answer:
        return WrittenAnswerGrade(
            question=item.question,
            user_answer=user_answer,
            score=0.0,
            status="No answer",
            matched_keywords=[],
            missing_keywords=[],
            matched_points=[],
            missing_points=[],
            sentence_feedback=[],
            expected_answer=expected_answer,
            explanation=explanation,
            page=item.page,
        )

    expected_similarity = text_similarity(user_answer, expected_answer)
    expected_support = source_support_score(user_answer, expected_answer)
    explanation_similarity = text_similarity(user_answer, explanation) if explanation else 0.0
    explanation_support = source_support_score(user_answer, explanation) if explanation else 0.0

    score = (
        expected_similarity * 4.0
        + expected_support * 3.5
        + explanation_similarity * 1.2
        + explanation_support * 1.3
    )

    if len(words_key(user_answer)) >= 6:
        score += 0.5

    score = round(min(10.0, score), 1)

    if score >= 8:
        status = "Correct"
    elif score >= 5:
        status = "Partially correct"
    else:
        status = "Needs review"

    feedback = [
        sentence_correctness(sentence, expected_answer, explanation)
        for sentence in split_user_sentences(user_answer)
    ]

    return WrittenAnswerGrade(
        question=item.question,
        user_answer=user_answer,
        score=score,
        status=status,
        matched_keywords=[],
        missing_keywords=[],
        matched_points=[],
        missing_points=[],
        sentence_feedback=feedback,
        expected_answer=expected_answer,
        explanation=explanation,
        page=item.page,
    )


def grade_written_answers(answers: list[WrittenUserAnswer]) -> WrittenGradeOutput:
    results = [grade_one_written_answer(item) for item in answers]
    total = round(sum(item.score for item in results), 1)
    percentage = round((total / max(1, len(results) * 10)) * 100, 1)
    return WrittenGradeOutput(total_score=total, percentage=percentage, results=results)


# =========================================================
# ROUTES
# =========================================================

@app.get("/")
async def root():
    return {
        "message": "StudyFlow local AI backend is running",
        "summary_model": SUMMARY_MODEL,
        "quiz_model": QUIZ_MODEL,
        "quiz_mode": "phi4_mini_mcq_plus_written_quiz",
        "docs": "/docs",
        "health": "/health",
        "summary_text_endpoint_1": "/conversation",
        "summary_text_endpoint_2": "/summarize",
        "summary_file_endpoint": "/file/upload",
        "quiz_text_endpoint": "/quiz/text",
        "quiz_file_endpoint": "/quiz/file/upload",
        "written_quiz_text_endpoint": "/written-quiz/text",
        "written_quiz_file_endpoint": "/written-quiz/file/upload",
        "written_quiz_grade_endpoint": "/written-quiz/grade",
    }


@app.get("/health")
async def health():
    return {
        "status": "ok",
        "summary_model": SUMMARY_MODEL,
        "quiz_model": QUIZ_MODEL,
        "quiz_mode": "phi4_mini_mcq_plus_written_quiz",
        "ollama_base_url": OLLAMA_BASE_URL,
        "quiz_num_ctx": QUIZ_NUM_CTX,
        "quiz_num_predict": QUIZ_NUM_PREDICT,
        "quiz_max_context_chars": QUIZ_MAX_CONTEXT_CHARS,
    }


@app.post("/conversation", response_model=SummaryOutput)
async def conversation(input: Input):
    start_time = time.time()
    output_text = summarize_uploaded_text(input.human_input)
    processing_time = round(time.time() - start_time, 2)
    return SummaryOutput(
        output=output_text,
        summary=output_text,
        result=output_text,
        processing_time_seconds=processing_time,
        processing_time_minutes=round(processing_time / 60, 2),
    )


@app.post("/summarize", response_model=SummaryOutput)
async def summarize(input: SummaryInput):
    start_time = time.time()
    text = input.text or input.human_input or ""
    output_text = summarize_uploaded_text(text)
    processing_time = round(time.time() - start_time, 2)
    return SummaryOutput(
        output=output_text,
        summary=output_text,
        result=output_text,
        processing_time_seconds=processing_time,
        processing_time_minutes=round(processing_time / 60, 2),
    )


@app.post("/file/upload", response_model=dict)
async def upload_file_summary(uploaded_file: UploadFile = File(...)):
    start_time = time.time()

    try:
        file_bytes = await uploaded_file.read()

        if is_pdf_file(uploaded_file):
            text_content = extract_pdf_text(file_bytes)
            file_type = "pdf"
        elif is_txt_file(uploaded_file):
            text_content = clean_source_text(decode_txt_bytes(file_bytes))
            file_type = "txt"
        else:
            raise HTTPException(status_code=400, detail="Invalid file type. Please upload a PDF or TXT file.")

        if not text_content or len(text_content.strip()) < 50:
            raise HTTPException(status_code=422, detail="Not enough readable text found.")

        output = summarize_uploaded_text(text_content)
        processing_time = round(time.time() - start_time, 2)

        return {
            "message": "Processing successful",
            "model": SUMMARY_MODEL,
            "file_type": file_type,
            "processing_time_seconds": processing_time,
            "processing_time_minutes": round(processing_time / 60, 2),
            "result": output,
            "summary": output,
            "output": output,
        }

    except HTTPException:
        raise
    except Exception as e:
        processing_time = round(time.time() - start_time, 2)
        logger.exception(f"Summary file upload failed after {processing_time} seconds")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/quiz/text", response_model=QuizOutput)
async def quiz_from_text(input: QuizInput):
    start_time = time.time()
    difficulty = normalize_difficulty(input.difficulty)
    questions, raw_output = generate_quiz_from_text(
        text=input.text,
        number_of_questions=input.number_of_questions,
        difficulty=difficulty,
    )
    processing_time = round(time.time() - start_time, 2)
    return QuizOutput(
        questions=questions,
        processing_time_seconds=processing_time,
        processing_time_minutes=round(processing_time / 60, 2),
        raw_output=raw_output,
    )


@app.post("/quiz/file/upload", response_model=dict)
async def upload_file_quiz(
    request: Request,
    uploaded_file: UploadFile = File(...),
    number_of_questions: int = Form(5),
    difficulty: str = Form("Medium"),
):
    start_time = time.time()

    try:
        query_number = request.query_params.get("number_of_questions")
        query_difficulty = request.query_params.get("difficulty")

        if query_number:
            number_of_questions = clamp_question_count(query_number)
        if query_difficulty:
            difficulty = query_difficulty

        number_of_questions = clamp_question_count(number_of_questions)
        difficulty = normalize_difficulty(difficulty)

        file_bytes = await uploaded_file.read()

        if is_pdf_file(uploaded_file):
            text_content = extract_pdf_text(file_bytes)
            file_type = "pdf"
        elif is_txt_file(uploaded_file):
            text_content = clean_source_text(decode_txt_bytes(file_bytes))
            file_type = "txt"
        else:
            raise HTTPException(status_code=400, detail="Invalid file type. Please upload a PDF or TXT file.")

        if not text_content or len(text_content.strip()) < 100:
            raise HTTPException(status_code=422, detail="Not enough readable text found to generate a quiz.")

        questions, raw_output = generate_quiz_from_text(
            text=text_content,
            number_of_questions=number_of_questions,
            difficulty=difficulty,
        )

        processing_time = round(time.time() - start_time, 2)

        return {
            "message": "Quiz generation successful",
            "model": QUIZ_MODEL,
            "quiz_mode": "phi4_mini_mcq_plus_written_quiz",
            "file_type": file_type,
            "difficulty": display_difficulty(difficulty),
            "difficulty_internal": difficulty,
            "number_of_questions": number_of_questions,
            "processing_time_seconds": processing_time,
            "processing_time_minutes": round(processing_time / 60, 2),
            "questions": [model_to_dict(q) for q in questions],
            "raw_output": raw_output,
        }

    except HTTPException:
        raise
    except Exception as e:
        processing_time = round(time.time() - start_time, 2)
        logger.exception(f"Quiz generation failed after {processing_time} seconds")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/written-quiz/text", response_model=WrittenQuizOutput)
@app.post("/quiz/written/text", response_model=WrittenQuizOutput)
async def written_quiz_from_text(input: WrittenQuizInput):
    start_time = time.time()
    difficulty = normalize_difficulty(input.difficulty)
    questions, raw_output = generate_written_quiz_from_text(
        text=input.text,
        number_of_questions=input.number_of_questions,
        difficulty=difficulty,
    )
    processing_time = round(time.time() - start_time, 2)
    return WrittenQuizOutput(
        questions=questions,
        processing_time_seconds=processing_time,
        processing_time_minutes=round(processing_time / 60, 2),
        raw_output=raw_output,
    )


@app.post("/written-quiz/file/upload", response_model=dict)
@app.post("/quiz/written/file/upload", response_model=dict)
async def upload_file_written_quiz(
    request: Request,
    uploaded_file: UploadFile = File(...),
    number_of_questions: int = Form(5),
    difficulty: str = Form("Mixed"),
):
    start_time = time.time()

    try:
        query_number = request.query_params.get("number_of_questions")
        query_difficulty = request.query_params.get("difficulty")

        if query_number:
            number_of_questions = clamp_question_count(query_number)
        if query_difficulty:
            difficulty = query_difficulty

        number_of_questions = clamp_question_count(number_of_questions)
        difficulty = normalize_difficulty(difficulty)

        file_bytes = await uploaded_file.read()

        if is_pdf_file(uploaded_file):
            text_content = extract_pdf_text(file_bytes)
            file_type = "pdf"
        elif is_txt_file(uploaded_file):
            text_content = clean_source_text(decode_txt_bytes(file_bytes))
            file_type = "txt"
        else:
            raise HTTPException(status_code=400, detail="Invalid file type. Please upload a PDF or TXT file.")

        if not text_content or len(text_content.strip()) < 100:
            raise HTTPException(status_code=422, detail="Not enough readable text found to generate a written quiz.")

        questions, raw_output = generate_written_quiz_from_text(
            text=text_content,
            number_of_questions=number_of_questions,
            difficulty=difficulty,
        )

        processing_time = round(time.time() - start_time, 2)

        return {
            "message": "Written quiz generation successful",
            "model": QUIZ_MODEL,
            "quiz_mode": "written_5_questions_local_submit_grading",
            "file_type": file_type,
            "difficulty": display_difficulty(difficulty),
            "difficulty_internal": difficulty,
            "number_of_questions": number_of_questions,
            "processing_time_seconds": processing_time,
            "processing_time_minutes": round(processing_time / 60, 2),
            "questions": [model_to_dict(q) for q in questions],
            "raw_output": raw_output,
        }

    except HTTPException:
        raise
    except Exception as e:
        processing_time = round(time.time() - start_time, 2)
        logger.exception(f"Written quiz generation failed after {processing_time} seconds")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/written-quiz/grade", response_model=WrittenGradeOutput)
@app.post("/quiz/written/grade", response_model=WrittenGradeOutput)
async def grade_written_quiz(input: WrittenGradeInput):
    return grade_written_answers(input.answers)
